### ISSUE TITLE
Spawners not dropping on old world

### ISSUE THREAD

**Issue by WellSure** [katanya04/mine-spawners#2]
When I downloaded the mod I already had a world. I broke a spawner and it dropped, every spawner after that didnt drop anything, not even xp. On a newly created world it works just fine. Im not sure if this is a bug with the mod or its just my world being weird.

**Comment by katanya04** [comment]
Hi! Which version of minecraft and which version of the mod were you using? In which version was the world created?

**Comment by WellSure** [comment]
> Hi! Which version of minecraft and which version of the mod were you using? In which version was the world created?

The minecraft, mod, and world are all 1.20.6.

**Comment by WellSure** [comment]
Hey! for some reason it just started working again... I did mess around with settings in my world and i guess one of them fixed it. Anyways Im sorry and thanks!

**Comment by WellSure** [comment]
Completely regard my last comment, I thought it was working but I've figured it out. For some reason it only works for a little bit after you join. Once you join and break a spawner it works fine, but after a little while and you break a spawner it just doesn't drop.

**Comment by katanya04** [comment]
Are you testing this on a singleplayer world or in a fabric server? Are you doing any specific actions to trigger this state in which it stops working?

**Comment by AlexTheSuprWolf** [comment]
I am also having this issue, no spawners will drop in my Singleplayer Survival World, natural or manually placed. Unfortunately, despite an hour of testing everything I could think of, I have been unable to determine the cause. Newly created worlds, even ones generated without the mod installed function perfectly fine. I even tested loading in the spawner's chunk without the mod installed, then adding the mod and it still worked fine. It just won't work in the survival world for some reason.

I suggest adding a failsafe to the mod temporarily until the root cause is found.

**Comment by katanya04** [comment]
Was that world created on an old version? Or, could you share that world folder with me so i can test it? I haven't been able to replicate this issue

**Comment by AlexTheSuprWolf** [comment]
nope. Fabric 1.20.6. Fabric api did update once in the middle of my play though but if that were the issue, the other test worlds on the same homebrew modpack would have also broken. let me first copy the world over to an instance where only your mod is installed first and see if the error persists, just to be sure it's not a strange mod conflict.

**Comment by AlexTheSuprWolf** [comment]
yep, the issue persists. it will work fine for the first minute or so, then completely stops working. the world has to be loaded for a bit first, though. like, 2 minutes.

How would you like me to send you the world? I have the zip ready.

**Comment by katanya04** [comment]
Mmm you can send it to my email, katanya024@gmail.com, or you can upload it to your drive and send me the link, or if you prefer to not share your email with me you can put it on mediafire or similar webs

**Comment by AlexTheSuprWolf** [comment]
just emailed you the google drive link

**Comment by katanya04** [comment]
Thanks, I'll check it as soon as I can

**Comment by katanya04** [comment]
Should be fixed now.
Opening the Minecraft console, I could check that it would stop working as soon as Minecraft reloaded the advancements. The method player::getActiveHand would return the opposite hand after that moment, and it was checking if you had a pickaxe in the incorrect hand. I don't know if that's a Minecraft bug or a Fabric bug, but eitherway, I changed it so it uses the method player::getMainHandStack, which seems to work correctly all the time
If you can, try again with mod version 1.3.2 just to confirm it indeed works (I already did but you know, just in case)

**Comment by AlexTheSuprWolf** [comment]
Everything is working perfectly now in the new version.

As for the broken version, was able to break all my test worlds consistently now. it's not actually the advancements. using anything usable in your offhand, like a shield, makes that the active hand by the game's logic. I am able to consistently "unbreak" the mod by taking the shield out of my offhand, putting it in my hotbar and blocking with it.

also found in the broken version that having the silk in your offhand when the bug was active and mining with a regular pickaxe gives both the spawner and xp, meaning the new version has also patched an infinite xp exploit. 2 birds with one stone

**Comment by katanya04** [comment]
I see, very nice. Well then, I'll close this issue. Thank you both for the help :)
